In [1]:
# basic of neurons
inputs = [1, 2, 3,2.5]
weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bisas1 = 2
bisas2 = 3
bisas3 = 0.5
output = []


In [2]:
# conmparison
list_of_output = [ inputs[0]*weights1[0]+ inputs[1]*weights1[1]+ inputs[2]*weights1[2]+inputs[3]*weights1[3]+bisas1,  
                   inputs[0]*weights2[0]+ inputs[1]*weights2[1]+ inputs[2]*weights2[2]+inputs[3]*weights2[3]+bisas2, 
                   inputs[0]*weights3[0]+ inputs[1]*weights3[1]+ inputs[2]*weights3[2]+inputs[3]*weights3[3]+bisas3
                 ]
print(list_of_output)

[4.8, 1.21, 2.385]


In [3]:
# using more dynamic way 
inputs = [1, 2, 3,2.5]
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5,-0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87] 
    ]
biases = [2,3,0.5]
zipped =zip(weights,biases)
print(tuple(zipped))  

(([0.2, 0.8, -0.5, 1.0], 2), ([0.5, -0.91, 0.26, -0.5], 3), ([-0.26, -0.27, 0.17, 0.87], 0.5))


In [4]:
layer_outputs = [] # output of current layer
for neuron_weights,neuron_bias in zip(weights, biases):
    neuron_output = 0 # output of given neuron
    for n_input, weight in zip(inputs,neuron_weights):
        neuron_output += n_input*weight
    neuron_output +=neuron_bias
    layer_outputs.append(neuron_output)
print(layer_outputs)   

[4.8, 1.21, 2.385]


In [5]:
# dot product 
import numpy as np
inputs = [1, 2, 3,2.5]
weights1 = [0.2, 0.8, -0.5, 1.0]
bias = 2
output = np.dot(inputs, weights1)+bias
print(output)

4.8


In [6]:
inputs = [1, 2, 3,2.5]
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5,-0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87] 
    ]
biases = [2,3,0.5]
output = np.dot(weights,inputs)+biases
print(output)

[4.8   1.21  2.385]


## How Does that Dot Product actually working

In [7]:
output_detail = [np.dot(weights[0],inputs),
                np.dot(weights[1],inputs),
                np.dot(weights[2], inputs),
                ]
bias = np.array(biases)
print(output_detail + bias )

[4.8   1.21  2.385]


## Layer 1

In [8]:
inputs_layer1 = [
    [1,2,3,2.5],
    [2.0,5.0,-1.0,2.0],
    [-1.5,2.7,3.3,-0.8],
    ]

weights_layer1 = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5,-0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87] 
    ]
bias_layer1 = [2,3,0.5]
out_put_layer1 = np.dot(inputs_layer1,np.array(weights_layer1).T)+bias_layer1
out_put_layer1

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

## layer 2

In [9]:
weights_layer2 = [
[0.1,-0.14,0.5],
[-0.5,0.12,-0.33],
[-0.44, 0.73, -0.13]
]
bias_layer2 = [-1,2,-0.5]
out_put_layer2 = np.dot(out_put_layer1, np.array(weights_layer2).T)+bias_layer2
out_put_layer2

array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])

In [10]:
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

X,y = spiral_data(100,3)


class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1*np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1,n_neurons))
        
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights)+ self.biases

class Activation_ReLu:
    def forward(self,inputs):
        self.output = np.maximum(0,inputs)

class Activation_softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities 


In [11]:
layer1 = Layer_Dense(2,5)
activation1 = Activation_ReLu()
layer2 = Layer_Dense(5,3)
activation2 = Activation_softmax()
layer1.forward(X)
activation1.forward(layer1.output)
layer2.forward(activation1.output)
activation2.forward(layer2.output)
activation2.output

array([[0.33333334, 0.33333334, 0.33333334],
       [0.33334148, 0.3333302 , 0.33332834],
       [0.33335316, 0.33332598, 0.33332086],
       [0.333332  , 0.33330762, 0.3333604 ],
       [0.33333603, 0.33330083, 0.33336315],
       [0.33338383, 0.33331344, 0.3333027 ],
       [0.3333572 , 0.33329478, 0.33334807],
       [0.33340374, 0.3333082 , 0.3332881 ],
       [0.33339977, 0.33330202, 0.3332982 ],
       [0.33336535, 0.3332733 , 0.33336142],
       [0.33337295, 0.333269  , 0.33335805],
       [0.3332787 , 0.33321112, 0.33351016],
       [0.33330157, 0.33322194, 0.33347648],
       [0.33333594, 0.33322513, 0.33343893],
       [0.33328852, 0.33320144, 0.33351007],
       [0.3332781 , 0.33318755, 0.33353442],
       [0.33320153, 0.33311486, 0.33368364],
       [0.33328357, 0.3331743 , 0.33354214],
       [0.3332255 , 0.3331155 , 0.33365905],
       [0.33330777, 0.33316433, 0.3335279 ],
       [0.33350578, 0.33325595, 0.33323827],
       [0.33315322, 0.33304507, 0.33380166],
       [0.

## RELU Activation Function

In [12]:
inputs_for_relu = [0,2,-1,3.3,-2.7,1.1,2.2,-100]
outputs_of_relu = []
for i in inputs_for_relu:
    if i>0:
        outputs_of_relu.append(i)
    elif i<=0:
        outputs_of_relu.append(0)
print(outputs_of_relu)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


## softmax Function

In [13]:
import math
layer_outputs = [4.8, 1.21, 2.385]
E = math.e
exp_values = []
for output in layer_outputs:
    exp_values.append(E**output)
print(exp_values)
norm_base = sum(exp_values)
norm_value = []

for values in exp_values:
    norm_value.append(values/norm_base)
print(norm_value)
print(sum(norm_value))

[121.51041751873483, 3.353484652549023, 10.859062664920513]
[0.8952826639572619, 0.024708306782099374, 0.0800090292606387]
0.9999999999999999


## softmax for batch

In [14]:
import numpy as np

layer_output = [
    [4.8, 1.21, 2.385],
    [8.9, -1.81, 0.2],
    [1.41, 1.051, 0.026]
]

exp_values = np.exp(layer_output)
print(exp_values)
sums = np.sum(exp_values, axis=1, keepdims=True)
print(sums)

[[1.21510418e+02 3.35348465e+00 1.08590627e+01]
 [7.33197354e+03 1.63654137e-01 1.22140276e+00]
 [4.09595540e+00 2.86051020e+00 1.02634095e+00]]
[[ 135.72296484]
 [7333.35859605]
 [   7.98280655]]


## Loss function

In [18]:
import math
softmax_output = [0.7,0.1, 0.2]
target_output = [1,0,0]
loss = -(math.log(softmax_output[0])*target_output[0]+
        math.log(softmax_output[1])*target_output[1]+
        math.log(softmax_output[2])*target_output[2]
        )
print(loss)

0.35667494393873245


## for Batch

In [19]:
softmax_outputs = np.array([[0.7,0.1, 0.2],
                           [0.1,0.5,0.4],
                           [0.02, 0.9, 0.08]])
class_targets = [0,1,1]
print(softmax_outputs[[0,1,2], class_targets])

[0.7 0.5 0.9]
