In [1]:
# basic of neurons
inputs = [1, 2, 3,2.5]
weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bisas1 = 2
bisas2 = 3
bisas3 = 0.5
output = []


In [2]:
# conmparison
list_of_output = [ inputs[0]*weights1[0]+ inputs[1]*weights1[1]+ inputs[2]*weights1[2]+inputs[3]*weights1[3]+bisas1,  
                   inputs[0]*weights2[0]+ inputs[1]*weights2[1]+ inputs[2]*weights2[2]+inputs[3]*weights2[3]+bisas2, 
                   inputs[0]*weights3[0]+ inputs[1]*weights3[1]+ inputs[2]*weights3[2]+inputs[3]*weights3[3]+bisas3
                 ]
print(list_of_output)

[4.8, 1.21, 2.385]


In [3]:
# using more dynamic way 
inputs = [1, 2, 3,2.5]
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5,-0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87] 
    ]
biases = [2,3,0.5]
zipped =zip(weights,biases)
print(tuple(zipped))  

(([0.2, 0.8, -0.5, 1.0], 2), ([0.5, -0.91, 0.26, -0.5], 3), ([-0.26, -0.27, 0.17, 0.87], 0.5))


In [4]:
layer_outputs = [] # output of current layer
for neuron_weights,neuron_bias in zip(weights, biases):
    neuron_output = 0 # output of given neuron
    for n_input, weight in zip(inputs,neuron_weights):
        neuron_output += n_input*weight
    neuron_output +=neuron_bias
    layer_outputs.append(neuron_output)
print(layer_outputs)   

[4.8, 1.21, 2.385]


In [5]:
# dot product 
import numpy as np
inputs = [1, 2, 3,2.5]
weights1 = [0.2, 0.8, -0.5, 1.0]
bias = 2
output = np.dot(inputs, weights1)+bias
print(output)

4.8


In [6]:
inputs = [1, 2, 3,2.5]
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5,-0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87] 
    ]
biases = [2,3,0.5]
output = np.dot(weights,inputs)+biases
print(output)

[4.8   1.21  2.385]


## How Does that Dot Product actually working

In [7]:
output_detail = [np.dot(weights[0],inputs),
                np.dot(weights[1],inputs),
                np.dot(weights[2], inputs),
                ]
bias = np.array(biases)
print(output_detail + bias )

[4.8   1.21  2.385]


## Layer 1

In [11]:
inputs_layer1 = [
    [1,2,3,2.5],
    [2.0,5.0,-1.0,2.0],
    [-1.5,2.7,3.3,-0.8],
    ]

weights_layer1 = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5,-0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87] 
    ]
bias_layer1 = [2,3,0.5]
out_put_layer1 = np.dot(inputs_layer1,np.array(weights_layer1).T)+bias_layer1
out_put_layer1

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

## layer 2

In [12]:
weights_layer2 = [
[0.1,-0.14,0.5],
[-0.5,0.12,-0.33],
[-0.44, 0.73, -0.13]
]
bias_layer2 = [-1,2,-0.5]
out_put_layer2 = np.dot(out_put_layer1, np.array(weights_layer2).T)+bias_layer2
out_put_layer2

array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])

In [24]:
np.random.seed(0)
X = [
    [1,2,3,2.5],
    [2.0,5.0,-1.0,2.0],
    [-1.5,2.7,3.3,-0.8],
    ]
class Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1*np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1,n_neurons))
        
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights)+ self.biases

In [25]:
layer1 = Dense(4,5)
layer2 = Dense(4,2)
layer1.forward(X)
print(layer1.output)

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]
