In [2]:
import numpy as np

class Tensor:
    def __init__(self, data, _children=(), _op=''):
        self.data = np.array(data, dtype=np.float32)
        self.grad = np.zeros_like(self.data)
        self._prev = set(_children)
        self._op = _op
        self._backward = lambda: None  

    def sum(self):
        out = Tensor(self.data.sum(),(self,), 'sum')
        def _backward():
            self.grad += np.ones_like(self.data) * out.grad
        out. _backward = _backward
        return out

    def mean(self):
        n_elements = self.data.size
        out = Tensor(self.data.mean(), (self,), 'mean')

        def _backward():
            self.grad += np.ones_like(self.data) * (out.grad / n_elements)
        out._backward = _backward
        return out

    def reshape(self, *shape):
        out = Tensor(self.data.reshape(*shape),(self,), 'reshape')

        def _backward():
            self.grad += out.grad.reshape(self.data.shape)
        out._backward = _backward
        return out
        
    @property
    def T(self):
        out = Tensor(self.data.T, (self,), 'T')

        def _backward():
            self.grad += out.grad.T
        out._backward = _backward
        return out

    def __add__(self, other):
        other = other if isinstance(other, Tensor) else Tensor(other)
        out = Tensor(self.data + other.data, (self, other), '+')

    
        def _backward():
            self.grad += out.grad * 1.0
            other.grad += out.grad * 1.0
        out._backward = _backward
        return out

    def __sub__(self, other):
        other = other if isinstance(other, Tensor) else Tensor(other)
        out = Tensor(self.data - other.data, (self, other), '-')

        def _backward():
            self.grad += out.grad*1.0
            other.grad += out.grad*(-1.0)
        out._backward = _backward
        return out

    def __truediv__(self, other):
        other = other if isinstance(other, Tensor) else Tensor(other)
        out = Tensor(self.data / other.data, (self,other), '/')

        def _backward():
            self.grad +=(1.0/other.data)*out.grad
            other.grad +=(-self.data/(other.data**2))*out.grad
        out._backward = _backward
        return out

    def __mul__(self, other):
        other = other if isinstance(other, Tensor) else Tensor(other)
        out = Tensor(self.data * other.data, (self, other), '*')

        def _backward():
            self.grad += other.data * out.grad
            other.grad += self.data * out.grad
        out._backward = _backward
        return out

    def __pow__(self, power):
        assert isinstance( power, (int, float)),"power must be scaler"
        out = Tensor(self.data ** power,(self,), f'**{power}')

        def _backward():
            self.grad += (power * self.data ** (power-1))*out.grad
        out._backward = _backward
        return out

    def __matmul__(self,other):
        other = other if isinstance(other, Tensor) else Tensor(other)
        out = Tensor(self.data @ other.data, (self,other), '@')

        def _backward():
            self.grad += out.grad @ other.data.T
            other.grad += self.data.T @ out.grad
        out._backward = _backward
        return out

    def backward(self):
        # Topological sort of nodes to handle dependencies
        topo = []
        visited = set()
        def build_topo(t):
            if t not in visited:
                visited.add(t)
                for child in t._prev:
                    build_topo(child)
                topo.append(t)
        build_topo(self)

        # Initialize gradient of output
        self.grad = 1.0

        # Traverse nodes in reverse topological order
        for t in reversed(topo):
            t._backward()

    def __repr__(self):
        return f"Tensor(data={self.data}, grad={self.grad})"

In [14]:
X = Tensor(np.array([[1., 2.,],
                     [4., 5.,]]))

Y = X.T         
Y.grad = np.ones_like(Y.data)
Y._backward()

print("Y.data:\n", Y.data)
print("X.grad:\n", X.grad)

Y.data:
 [[1. 4.]
 [2. 5.]]
X.grad:
 [[1. 1.]
 [1. 1.]]


In [15]:
class Parameter(Tensor):
    """ 
    Trainable tensor
    used for weights and biases inside layers
    """
    def __init__(self, data, required_grad=True):
        super().__init__(data)
        self.required_grad = required_grad

In [18]:
w = Parameter (np.array([[1.,2.],
                        [3.,4.]]
                       ))
print("Data:\n",w.data)
print("Grad\n",w.grad)
print("Requires grad:",w.required_grad)
z= w + X
print("\n results of w + x (Tensor)",z)
print("Z is parameter?",isinstance(z, Parameter))
print("\nz.data:\n",z.data)
z.backward()
print("\n Grad after backward:")
print("w.grad:\n",w.grad)
print("x.grad:\n",X.grad)


Data:
 [[1. 2.]
 [3. 4.]]
Grad
 [[0. 0.]
 [0. 0.]]
Requires grad: True

 results of w + x (Tensor) Tensor(data=[[2. 4.]
 [7. 9.]], grad=[[0. 0.]
 [0. 0.]])
Z is parameter? False

z.data:
 [[2. 4.]
 [7. 9.]]

 Grad after backward:
w.grad:
 [[1. 1.]
 [1. 1.]]
x.grad:
 [[3. 3.]
 [3. 3.]]


In [2]:
# ann_engine/layers/base.py
class Module:
    """
    Base class for all layers 
    Holds trainable Parameters
    """
    def __init__(self):
        self ._parameters = {}

    def forward(self, *inputs):
        """
        define in child class .
        """
        raise NotImplementedError

    def __setattr__(self, name, value):
        """
        override setattr to track Parameters automatically.
        """
        from ann_engine.core.parameter import Parameter
        if isinstance(value, Parameter):
            if not hasattr(self, "_parameters"):
                super()._parameters[name] = value
            super().__setattr__(name, value)

    def parameters(self):
        """
        Return all Parameters of the module.
        """
        return list(self._parameters.values())

In [ ]:
from ann_engine.core.parameter import Parameter

class DummyLayer(Module):
    def __init__(self):
        super().__init__()
        self.w = Parameter(np.array([[1.,2.]]))